### ISSUE TITLE
Can't build on FreeBSD 14.1

### ISSUE THREAD

**Issue by ndeffayet** [NigelCunningham/pam-MySQL#90]
Version: 1.0.0-beta3
OS: FreeBSD 14.1-RELEASE
MariaDB 11.4.2

Unable to build using ninja:

[6/93] Compiling C object pam_mysql.so.p/src_logging.c.o
FAILED: pam_mysql.so.p/src_logging.c.o 
cc -Ipam_mysql.so.p -I. -I../pam-MySQL-1.0.0-beta3 -I/usr/include/mysql -I/usr/include/mysql/mysql -I/usr/include/mysql/ -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O0 -g -DHAVE_CONFIG_H -fPIC -MD -MQ pam_mysql.so.p/src_logging.c.o -MF pam_mysql.so.p/src_logging.c.o.d -o pam_mysql.so.p/src_logging.c.o -c ../pam-MySQL-1.0.0-beta3/src/logging.c
../pam-MySQL-1.0.0-beta3/src/logging.c:34:14: error: incompatible integer to pointer conversion returning 'int' from a function with result type 'char *' [-Wint-conversion]
   34 |       return PAM_MYSQL_ERR_ALLOC;
      |              ^~~~~~~~~~~~~~~~~~~
../pam-MySQL-1.0.0-beta3/src/logging.c:37:14: error: incompatible integer to pointer conversion returning 'int' from a function with result type 'char *' [-Wint-conversion]
   37 |       return PAM_MYSQL_ERR_UNKNOWN;
      |              ^~~~~~~~~~~~~~~~~~~~~
../pam-MySQL-1.0.0-beta3/src/logging.c:47:16: error: incompatible integer to pointer conversion returning 'int' from a function with result type 'char *' [-Wint-conversion]
   47 |         return PAM_MYSQL_ERR_ALLOC;
      |                ^~~~~~~~~~~~~~~~~~~
../pam-MySQL-1.0.0-beta3/src/logging.c:55:16: error: incompatible integer to pointer conversion returning 'int' from a function with result type 'char *' [-Wint-conversion]
   55 |         return PAM_MYSQL_ERR_UNKNOWN;
      |                ^~~~~~~~~~~~~~~~~~~~~
../pam-MySQL-1.0.0-beta3/src/logging.c:83:14: error: incompatible integer to pointer conversion returning 'int' from a function with result type 'char *' [-Wint-conversion]
   83 |       return PAM_MYSQL_ERR_NOTIMPL;
      |              ^~~~~~~~~~~~~~~~~~~~~
../pam-MySQL-1.0.0-beta3/src/logging.c:91:3: warning: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
   91 |   retval = _try_get_addr_info(hostname);
      |   ^
      |   int
../pam-MySQL-1.0.0-beta3/src/logging.c:91:31: error: use of undeclared identifier 'hostname'; did you mean 'ptsname'?
   91 |   retval = _try_get_addr_info(hostname);
      |                               ^~~~~~~~
      |                               ptsname
/usr/include/stdlib.h:236:7: note: 'ptsname' declared here
  236 | char    *ptsname(int);
      |          ^
../pam-MySQL-1.0.0-beta3/src/logging.c:91:3: error: incompatible pointer to integer conversion initializing 'int' with an expression of type 'char *' [-Wint-conversion]
   91 |   retval = _try_get_addr_info(hostname);
      |   ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../pam-MySQL-1.0.0-beta3/src/logging.c:91:12: error: initializer element is not a compile-time constant
   91 |   retval = _try_get_addr_info(hostname);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../pam-MySQL-1.0.0-beta3/src/logging.c:93:3: error: expected identifier or '('
   93 |   if (IS_ERR(retval)) {
      |   ^
../pam-MySQL-1.0.0-beta3/src/logging.c:97:1: error: extraneous closing brace ('}')
   97 | }
      | ^
../pam-MySQL-1.0.0-beta3/src/logging.c:252:1: error: function definition is not allowed here
  252 | {
      | ^
../pam-MySQL-1.0.0-beta3/src/logging.c:337:1: error: expected '}'
  337 | 
      | ^
../pam-MySQL-1.0.0-beta3/src/logging.c:215:1: note: to match this '{'
  215 | {
      | ^
1 warning and 12 errors generated.
[7/93] Compiling C object pam_mysql.so.p/src_mysql.c.o
ninja: build stopped: subcommand failed.
